version: '3'

services:
  mongo-server:
    image: mongo:4.2-bionic
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - /home/bean/Twitch/cachingServer/data/mongo/data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  redis-server:
    image: redis
    command: >
      --requirepass ${REDIS_PASSWORD}
    volumes:
      - /home/bean/Twitch/cachingServer/data/redis/data:/data
  
  caching-server:
    build: .
    restart: on-failure:5 # max 5 restart tries 
    ports:
      - '8001:8001'
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MONGO_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
